<!-- MHonArc v2.6.16 -->
<!--X-Subject: Nested exception from sub processor -->
<!--X-From-R13: "H.H." <iibfgevNtznvy.pbz> -->
<!--X-Date: Fri, 07 Oct 2011 22:29:21 +0200 -->
<!--X-Message-Id: CAO2iSXE1ycB4KX1vxqk15CxbW1rpWczZAyR_bX1g6j+yA2PCTQ@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Nested exception from sub processor -- October 07, 2011 - 22:29</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Nested exception from sub processor</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00008" class="tabs">Index by Date</a> | <a href="threads.html#00008" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00007.html">Date Prev</a>] [<a href="msg00009.html">Date Next</a>] [<a href="msg00001.html">Thread Prev</a>] [<a href="msg00009.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: &quot;Edward d'Auvergne&quot; &lt;edward@xxxxxxxxxxxxx&gt;, relax-users@xxxxxxx</li>
<li class="menuitem">
<em>Date</em>: Fri, 7 Oct 2011 15:28:32 -0500</li>
<li class="menuitem">
<em>Dkim-signature</em>: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=gamma;	h=mime-version:from:date:message-id:subject:to:content-type;	bh=rUkEWYZRIkf6hnk5KFTuCEwNfmpD22vT8tuAGSYxlV0=;	b=je67jscjR30W6pXuJT/8uW2LjlTn80KK7que8MfeHerLqhVd34LwudIVrfvOl35OHP	Cj+XxkVVg7z/9kh2AOre9Sebyk+AMHpsuzmDosh+xj7SKKIRmELlKCb8vjwcDQTMDO1b	XapPQZ/5ukmbgQqbTQsJ2Mm+R25lq5Se58k1c=</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00008.html">CAO2iSXE1ycB4KX1vxqk15CxbW1rpWczZAyR_bX1g6j+yA2PCTQ@mail.gmail.com</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>V.V.</strong> on October 07, 2011 - 22:29:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Hi Edward,

I am running &quot;dauvergne_protocol&quot; script for my protein. The
&quot;local_tm&quot; and &quot;sphere&quot; models calculations proceeded fine, but with
prolate/oblate/ellipsoid diffusion tensors an exception is thrown (the
output is below). I have run the same script successfully before. The
difference is that I have excluded several mobile residues and using
&quot;ave=False&quot; in &quot;structure.vectors&quot; (the pdb file is an NMR ensemble,
20 models). If necessary, I can send the input files separately. Relax
revision is 14809.

Thank you,
Vitaly

Traceback (most recent call last):
  File &quot;/home/vitalyv/relax/multi/uni_processor.py&quot;, line 136, in run
    self.callback.init_master(self)
  File &quot;/home/vitalyv/relax/multi/processor.py&quot;, line 263, in
default_init_master
    self.master.run()
  File &quot;/home/vitalyv/relax/relax.py&quot;, line 174, in run
    self.interpreter.run(self.script_file)
  File &quot;/home/vitalyv/relax/prompt/interpreter.py&quot;, line 300, in run
    return run_script(intro=self.__intro_string, local=locals(),
script_file=script_file, quit=self.__quit_flag,
show_script=self.__show_script,
raise_relax_error=self.__raise_relax_error)
  File &quot;/home/vitalyv/relax/prompt/interpreter.py&quot;, line 610, in run_script
    return console.interact(intro, local, script_file, quit,
show_script=show_script, raise_relax_error=raise_relax_error)
  File &quot;/home/vitalyv/relax/prompt/interpreter.py&quot;, line 495, in 
interact_script
    exec_script(script_file, local)
  File &quot;/home/vitalyv/relax/prompt/interpreter.py&quot;, line 383, in exec_script
    runpy.run_module(module, globals)
  File &quot;/usr/lib/python2.7/runpy.py&quot;, line 180, in run_module
    fname, loader, pkg_name)
  File &quot;/usr/lib/python2.7/runpy.py&quot;, line 72, in _run_code
    exec code in run_globals
  File &quot;/home/vitalyv/relax/wtpln/dauvergne_protocol.py&quot;, line 218, in 
&lt;module&gt;
    dAuvergne_protocol(pipe_name=name, diff_model=DIFF_MODEL,
mf_models=MF_MODELS, local_tm_models=LOCAL_TM_MODELS,
grid_inc=GRID_INC, min_algor=MIN_ALGOR, mc_sim_num=MC_NUM,
conv_loop=CONV_LOOP)
  File &quot;/home/vitalyv/relax/auto_analyses/dauvergne_protocol.py&quot;, line
223, in __init__
    self.execute()
  File &quot;/home/vitalyv/relax/auto_analyses/dauvergne_protocol.py&quot;, line
596, in execute
    self.interpreter.grid_search(inc=inc)
  File &quot;/home/vitalyv/relax/prompt/minimisation.py&quot;, line 106, in grid_search
    minimise.grid_search(lower=lower, upper=upper, inc=inc,
constraints=constraints, verbosity=verbosity)
  File &quot;/home/vitalyv/relax/generic_fns/minimise.py&quot;, line 146, in grid_search
    processor_box.processor.run_queue()
  File &quot;/home/vitalyv/relax/multi/uni_processor.py&quot;, line 149, in run_queue
    command.run(self, completed)
  File 
&quot;/home/vitalyv/relax/specific_fns/model_free/multi_processor_commands.py&quot;,
line 144, in run
    raise Capturing_exception(rank=processor.rank(), 
name=processor.get_name())
Capturing_exception:

------------------------------------------------------------------------------------------------------------------------

  File 
&quot;/home/vitalyv/relax/specific_fns/model_free/multi_processor_commands.py&quot;,
line 132, in run
    results = self.optimise()
  File 
&quot;/home/vitalyv/relax/specific_fns/model_free/multi_processor_commands.py&quot;,
line 185, in optimise
    results = grid_point_array(func=self.mf.func, args=(),
points=self.opt_params.subdivision,
verbosity=self.opt_params.verbosity)
  File &quot;/usr/lib/python2.7/site-packages/minfx/grid.py&quot;, line 282, in
grid_point_array
    f = func(*(points[k],)+args)
  File &quot;/home/vitalyv/relax/maths_fns/mf.py&quot;, line 517, in func_diff
    self.diff_data.calc_ci(data, self.diff_data)
  File &quot;/home/vitalyv/relax/maths_fns/weights.py&quot;, line 80, in 
calc_spheroid_ci
    data.ci[0] = 0.25 * data.three_dz2_one**2


Nested Exception from sub processor
Exception type: ValueError
Message: setting an array element with a sequence.


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00009" href="msg00009.html">Re: Nested exception from sub processor</a></strong>
<ul><li><em>From:</em> V.V.</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Mon Oct 17 23:40:09 2011</div>  
</body>
</html>
