<!-- MHonArc v2.6.16 -->
<!--X-Subject: Error when running full_analysis.y script &#45;&#45; part II -->
<!--X-From-R13: Rnavry Béerm <qnavry.crermNzby.ovby.rgum.pu> -->
<!--X-Date: Wed, 17 Mar 2010 08:58:47 +0100 -->
<!--X-Message-Id: B5846525&#45;70C1&#45;49C9&#45;BBFC&#45;4AA3EA494120@mol.biol.ethz.ch -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Error when running full_analysis.y script -- part II -- March 17, 2010 - 08:58</title>
<link rel="stylesheet" type="text/css" href="/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="https://gna.org/images/gna.theme/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Error when running full_analysis.y script -- part II</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00000" class="tabs">Index by Date</a> | <a href="threads.html#00000" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[Date Prev] [<a href="msg00001.html">Date Next</a>] [Thread Prev] [<a href="msg00001.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: &lt;relax-users@xxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Wed, 17 Mar 2010 08:55:54 +0100</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00000.html">B5846525-70C1-49C9-BBFC-4AA3EA494120@mol.biol.ethz.ch</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Daniel Pérez</strong> on March 17, 2010 - 08:58:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Hi Edward,

I hope you have some time to take a look at this. I have a data set at two 
fields. I used relax for fitting the data, but when and run the full_analysis 
script, after the software starts the grid search I get the following error 
message 

Traceback (most recent call last):
  File &quot;/soft/group/relax/relax-1.3.4/relax&quot;, line 418, in ?
    Relax()
  File &quot;/soft/group/relax/relax-1.3.4/relax&quot;, line 127, in __init__
    self.interpreter.run(self.script_file)
  File &quot;/soft/group/relax/relax-1.3.4/prompt/interpreter.py&quot;, line 276, in run
    return run_script(intro=self.__intro_string, local=self.local, 
script_file=script_file, quit=self.__quit_flag, 
show_script=self.__show_script, raise_relax_error=self.__raise_relax_error)
  File &quot;/soft/group/relax/relax-1.3.4/prompt/interpreter.py&quot;, line 537, in 
run_script
    return console.interact(intro, local, script_file, quit, 
show_script=show_script, raise_relax_error=raise_relax_error)
  File &quot;/soft/group/relax/relax-1.3.4/prompt/interpreter.py&quot;, line 433, in 
interact_script
    execfile(script_file, local)
  File &quot;full_analysis_markup.py&quot;, line 764, in ?
    Main(self.relax)
  File &quot;full_analysis_markup.py&quot;, line 226, in __init__
    self.multi_model(local_tm=True)
  File &quot;full_analysis_markup.py&quot;, line 755, in multi_model
    grid_search(inc=GRID_INC)
  File &quot;/soft/group/relax/relax-1.3.4/prompt/minimisation.py&quot;, line 156, in 
grid_search
    minimise.grid_search(lower=lower, upper=upper, inc=inc, 
constraints=constraints, verbosity=verbosity)
  File &quot;/soft/group/relax/relax-1.3.4/generic_fns/minimise.py&quot;, line 191, in 
grid_search
    grid_search(lower=lower, upper=upper, inc=inc, constraints=constraints, 
verbosity=verbosity)
  File 
&quot;/soft/group/relax/relax-1.3.4/specific_fns/model_free/mf_minimise.py&quot;, line 
479, in grid_search
    self.minimise(min_algor='grid', lower=lower, upper=upper, inc=inc, 
constraints=constraints, verbosity=verbosity, sim_index=sim_index)
  File 
&quot;/soft/group/relax/relax-1.3.4/specific_fns/model_free/mf_minimise.py&quot;, line 
789, in minimise
    model_type = self.determine_model_type()
  File &quot;/soft/group/relax/relax-1.3.4/specific_fns/model_free/main.py&quot;, line 
1015, in determine_model_type
    if cdp.diff_tensor.fixed:
AttributeError: 'PipeContainer' object has no attribute 'diff_tensor'


Checking the mailing archive I saw that Tiago Pais got the same error message 
last year.
That time you suggested him to use a script containing a markup:
<a  rel="nofollow" href="http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=9794&amp;view=markup">http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=9794&amp;view=markup</a>

(
The complete answer was:
Re: Error when running full_analysis.py script
Edward d'Auvergne
Tue, 27 Oct 2009 03:02:16 -0700

Dear Tiago,

This is a hard one to catch.  I have just added a function to this
script to check the validity of the user variables
(<a  rel="nofollow" href="http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=9794&amp;view=markup">http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=9794&amp;view=markup</a>).
 This should give better error messages specifically identifying the
problem.  For this second issue you are having, it is a little hard to
see what the problem is.  Would you be able to supply a little more
information.  For example the version of relax you are using, the full
error message, how you have executed the full_analysis.py script and
at what stage you are up to, etc.  With more information, I should be
able to track down the issue.

Cheers,

Edward
)



The traceback I showed to you above is coming from running that script, I got 
the same error message when I run the canonical full_analysis script.
I'm running relax 1.3.4 in RHEL distribution 5.1.19.6, kernel /vmlinuz 
2.6.18-128.1.10.e15

It will be nice if you can help me with this

Best regards

Daniel



Dr. Daniel Pérez
Institut für Molekularbiologie und Biophysik
Schafmattstrasse 20
ETH-Hönggerberg, HPK G 5
CH-8093 Zürich
Phone: +41 44 633 25 37
E-mail: daniel.perez@xxxxxxxxxxxxxxxx



</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00001" href="msg00001.html">Re: Error when running full_analysis.y script -- part II</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer">You are on the <a href="http://gna.org">Gna!</a> mail server.</div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Wed Mar 17 10:00:14 2010</div>  
</body>
</html>
