<!-- MHonArc v2.6.16 -->
<!--X-Subject: [bug #20469] Failure in reading X&#45;ray PDB files using the	ScientificPython parser. -->
<!--X-From-R13: Sqjneq q  Ohiretar <@A&#45;DSBZK.W@HOZWR&#45;ORRDSEENtan.bet> -->
<!--X-Date: Fri, 01 Feb 2013 11:53:33 +0100 -->
<!--X-Message-Id: 20130201&#45;105332.sv2782.81004@gna.org -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>[bug #20469] Failure in reading X-ray PDB files using the	ScientificPython parser. -- February 01, 2013 - 11:53</title>
<link rel="stylesheet" type="text/css" href="/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="https://gna.org/images/gna.theme/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />[bug #20469] Failure in reading X-ray PDB files using the	ScientificPython parser.</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00003" class="tabs">Index by Date</a> | <a href="threads.html#00003" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00002.html">Date Prev</a>] [<a href="msg00004.html">Date Next</a>] [<a href="msg00002.html">Thread Prev</a>] [<a href="msg00004.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Edward d  Auvergne &lt;edward@xxxxxxxxxxxxx&gt;, relax-devel@xxxxxxx</li>
<li class="menuitem">
<em>Date</em>: Fri, 01 Feb 2013 11:53:33 +0100</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00003.html">20130201-105332.sv2782.81004@gna.org</a>&gt;</li>
<li class="menuitem">
<em>References</em>: </li>
<li class="menuitem">
<em>User-agent</em>: Mozilla/5.0 (X11; Linux x86_64;	rv:10.0.11) Gecko/20100101 Firefox/10.0.11</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d Auvergne</strong> on February 01, 2013 - 11:53:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">URL:
  &lt;<a  rel="nofollow" href="http://gna.org/bugs/?20469">http://gna.org/bugs/?20469</a>&gt;

                 Summary: Failure in reading X-ray PDB files using the
ScientificPython parser.
                 Project: relax
            Submitted by: bugman
            Submitted on: Fri 01 Feb 2013 10:53:32 AM GMT
                Category: relax's source code
                Severity: 2 - Minor
                Priority: 3 - Low
                  Status: None
                 Privacy: Public
             Assigned to: bugman
         Originator Name: 
        Originator Email: 
             Open/Closed: Open
         Discussion Lock: Any
                 Release: 2.2.0
        Operating System: All systems

    _______________________________________________________

Details:

The presence of PDB crystallographic unit cell records triggers the following
bug:

Scientific Python PDB parser.
Traceback (most recent call last):
  File &quot;test_suite/system_tests/structure.py&quot;, line 63, in
test_bug_sr_2998_broken_conect_records
    self.interpreter.structure.read_pdb('1RTE_trunc.pdb', dir=path,
parser='scientific')
  File &quot;prompt/uf_objects.py&quot;, line 219, in __call__
    self._backend(*new_args, **uf_kargs)
  File &quot;generic_fns/structure/main.py&quot;, line 504, in read_pdb
    cdp.structure.load_pdb(file_path, read_mol=read_mol,
set_mol_name=set_mol_name, read_model=read_model, set_model_num=set_model_num,
verbosity=verbosity)
  File &quot;generic_fns/structure/scientific.py&quot;, line 602, in load_pdb
    model = PDB.Structure(file_path, model_num)
  File &quot;extern/scientific_python/IO/PDB.py&quot;, line 1160, in __init__
    self.parseFile(PDBFile(file_or_filename))
  File &quot;extern/scientific_python/IO/PDB.py&quot;, line 1381, in parseFile
    from extern.scientific_python.Geometry.Transformation \
ImportError: No module named Transformation





    _______________________________________________________

Reply to this item at:

  &lt;<a  rel="nofollow" href="http://gna.org/bugs/?20469">http://gna.org/bugs/?20469</a>&gt;

_______________________________________________
  Message sent via/by Gna!
  <a  rel="nofollow" href="http://gna.org/">http://gna.org/</a>



</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00004" href="msg00004.html">[bug #20469] Failure in reading X-ray PDB files using the	ScientificPython parser.</a></strong>
<ul><li><em>From:</em> Edward d Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer">You are on the <a href="http://gna.org">Gna!</a> mail server.</div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Fri Feb 01 15:40:09 2013</div>  
</body>
</html>
