<!-- MHonArc v2.6.16 -->
<!--X-Subject: Re: Problem during "final" run of d'Auvergne Protocol -->
<!--X-From-R13: "Sqjneq q'Ohiretar" <rqjneq.qnhiretarNtznvy.pbz> -->
<!--X-Date: Mon, 05 Mar 2012 09:33:58 +0100 -->
<!--X-Message-Id: CAED9pY&#45;O=jC&#45;w58UkK&#45;1rWQQH95_nrje2CgTtDBKOJm=eHWSiQ@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: CAJFDPzFu&#45;h1_=GKys3N7BOJbX&#45;QBbiAcF42v8W55EHb+NWMJNg@mail.gmail.com -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: Problem during &quot;final&quot; run of d'Auvergne Protocol -- March 05, 2012 - 09:33</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Re: Problem during &quot;final&quot; run of d'Auvergne Protocol</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00005" class="tabs">Index by Date</a> | <a href="threads.html#00005" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00004.html">Date Prev</a>] [<a href="msg00006.html">Date Next</a>] [<a href="msg00003.html">Thread Prev</a>] [<a href="msg00010.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Hugh RW Dannatt &lt;h.dannatt@xxxxxxxxxxxxxxx&gt;,	Gary Thompson &lt;garyt@xxxxxxxxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Mon, 5 Mar 2012 09:33:28 +0100</li>
<li class="menuitem">
<em>Authentication-results</em>: mr.google.com; spf=pass (google.com: domain of	edward.dauvergne@xxxxxxxxx designates 10.60.29.10 as permitted	sender) smtp.mail=edward.dauvergne@xxxxxxxxx;	dkim=pass header.i=edward.dauvergne@xxxxxxxxx</li>
<li class="menuitem">
<em>Cc</em>: &quot;relax-users@xxxxxxx&quot; &lt;relax-users@xxxxxxx&gt;</li>
<li class="menuitem">
<em>Dkim-signature</em>: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=20120113;	h=mime-version:in-reply-to:references:date:message-id:subject:from:to	:cc:content-type:content-transfer-encoding;	bh=R9y17uMdK9K9xlYvYvEE6Hf4ppvIbvuEUl5LjfLFs3M=;	b=mSJLh+7d+l/wSjY4gBf9CMdvwcb6Fnvi3IqqrJw1fttJNa6cJfaoCYydqxyEdxVa9A	I0AoA1iHT3TE2kg4ItDSYN/ENGnRMumxg+y2ntnA8+wijoRpKhWBjAIY0cnguY2F0sDE	ddoxLnazRfu2tTM9pgtGvS2Gr3umk9SO27Co9dhqZ2tk1GLVl2MNRq4xHCAKN2aXrBSm	M68GKX7F4aJydftzCV3C4X4BtNdnx+eBvXlGhsbzBpbiYiR9UEM2W2rISD651Zxpbg/H	NSpAwxgImp8xW9B0WWZ2BbyyB2IvSkVX44JrtVrk+RIHks5GoYfbbc4+bC+d2G55SwJM	P4rQ==</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00005.html">CAED9pY-O=jC-w58UkK-1rWQQH95_nrje2CgTtDBKOJm=eHWSiQ@mail.gmail.com</a>&gt;</li>
<li class="menuitem">
<em>References</em>: &lt;CAJFDPzFu-h1_=GKys3N7BOJbX-QBbiAcF42v8W55EHb+NWMJNg@xxxxxxxxxxxxxx&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d'Auvergne</strong> on March 05, 2012 - 09:33:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Hi Hugh,

I'm pretty sure this error has not been encountered before.  It at
least hasn't been reported.  I've never seen anything close to this
before, but I would guess that this is an infinitely recursive
exception (the error is being caught but, in the process, the error
occurs again, being caught a second time, then the 3rd error occurs,
is caught a 3rd time, with this continuing until your computer runs
out of RAM and swap space and relax is killed by the operating
system).  The error seems to occur within the error handing portion of
Gary Thompson's multi-processor framework (you are using the
uni-processor fabric of the framework here), so maybe Gary might know
a solution?

Is this error reproducible?  For testing, can you drop the number of
Monte Carlo simulations down to say 5?  Running relax with the debug
flag might also help:

$ relax --debug

or:

$ relax -d

Are you using the GUI or scripting user interface?  The output of:

$ relax --info

might also be useful.  As for your data set being too large, relax has
been used on much bigger systems before so this should not be an
issue.  One last thing, would you be able to create a bug report for
this error (<a  rel="nofollow" href="https://web.archive.org/web/https://gna.org/bugs/?func=additem&amp;group=relax">https://gna.org/bugs/?func=additem&amp;group=relax</a>)?  All of
the info/log files can then be pasted/attached there, and it is a
useful future reference for anyone who encounters the same or a
similar bug.

Cheers,

Edward



On 2 March 2012 12:33, Hugh RW Dannatt &lt;h.dannatt@xxxxxxxxxxxxxxx&gt; wrote:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Dear All,

Having completed the fitting of 1 dataset without any problems, I am
now moving onto another. Everything has worked fine until I change the
DIFF_MODEL to &quot;final&quot; and try to run the program again to get error
estimates on my fitted parameters.

The program successfully re-opens all the results file and selects the
diffusion model. Then all 500 simulations are done without issue, but
as soon as the program has finished this, it stops outputting anything
to the screen for a long time (&gt;12 hrs). During this time, the CPU and
Memory use is very high and the computer runs slowly. Eventually I get
a &quot;Memory Error&quot; and a whole load of messages outputted to the screen,
which I have pasted below. I should emphasize that all the stages of
running this program with different diffusion models have run fine,
and the computer I'm using is a relatively fast machine (dual core
Pentium 4, 2 GB RAM).

Has anyone had a similar problem? This dataset is larger than the
previous one which fit without issue (current one has 6 measurements
per 176 residues), but I can't imagine this being the cause of this
problem.

Thanks

Hugh

----

Simulation 485
Simulation 486
Simulation 487
Simulation 488
Simulation 489
Simulation 490
Simulation 491
Simulation 492
Simulation 493
Simulation 494
Simulation 495
Simulation 496
Simulation 497
Simulation 498
Simulation 499
Simulation 500


Traceback (most recent call last):
 File &quot;/progs/relax-1.3.13/multi/uni_processor.py&quot;, line 136, in run
   self.callback.init_master(self)
 File &quot;/progs/relax-1.3.13/multi/processor.py&quot;, line 263, in
default_init_master
   self.master.run()
 File &quot;/progs/relax-1.3.13/relax.py&quot;, line 171, in run
   self.interpreter.run(self.script_file)
 File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 300, in run
   return run_script(intro=self.__intro_string, local=locals(),
script_file=script_file, quit=self.__quit_flag,
show_script=self.__show_script,
raise_relax_error=self.__raise_relax_error)
 File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 610, in run_script
   return console.interact(intro, local, script_file, quit,
show_script=show_script, raise_relax_error=raise_relax_error)
 File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 495, in 
interact_script
   exec_script(script_file, local)
 File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 383, in exec_script
   runpy.run_module(module, globals)
 File &quot;/usr/lib/python2.6/runpy.py&quot;, line 140, in run_module
   fname, loader, pkg_name)
 File &quot;/usr/lib/python2.6/runpy.py&quot;, line 34, in _run_code
   exec code in run_globals
 File &quot;/home1/hugh/data/pgm298bq/relax/dauvergne_protocol.py&quot;, line
216, in &lt;module&gt;
   dAuvergne_protocol(pipe_name=name, diff_model=DIFF_MODEL,
mf_models=MF_MODELS, local_tm_models=LOCAL_TM_MODELS,
grid_inc=GRID_INC, min_algor=MIN_ALGOR, mc_sim_num=MC_NUM,
conv_loop=CONV_LOOP)
 File &quot;/progs/relax-1.3.13/auto_analyses/dauvergne_protocol.py&quot;, line
223, in __init__
Traceback (most recent call last):
 File &quot;/progs/Linux/bin/relax13&quot;, line 7, in &lt;module&gt;
   relax.start()
 File &quot;/progs/relax-1.3.13/relax.py&quot;, line 100, in start
   processor.run()
 File &quot;/progs/relax-1.3.13/multi/uni_processor.py&quot;, line 139, in run
   self.callback.handle_exception(self, e)
 File &quot;/progs/relax-1.3.13/multi/processor.py&quot;, line 250, in
default_handle_exception
   traceback.print_exc(file=sys.stderr)
 File &quot;/usr/lib/python2.6/traceback.py&quot;, line 227, in print_exc
   print_exception(etype, value, tb, limit, file)
 File &quot;/usr/lib/python2.6/traceback.py&quot;, line 125, in print_exception
   print_tb(tb, limit, file)
 File &quot;/usr/lib/python2.6/traceback.py&quot;, line 69, in print_tb
   line = linecache.getline(filename, lineno, f.f_globals)
 File &quot;/usr/lib/python2.6/linecache.py&quot;, line 14, in getline
   lines = getlines(filename, module_globals)
 File &quot;/usr/lib/python2.6/linecache.py&quot;, line 40, in getlines
   return updatecache(filename, module_globals)
 File &quot;/usr/lib/python2.6/linecache.py&quot;, line 136, in updatecache
   lines = fp.readlines()
MemoryError
9078.655u 666.933s 10:55:29.66 24.7%    0+0k 241482000+0io 6665721pf+0w

_______________________________________________
relax (<a  rel="nofollow" href="http://nmr-relax.com">http://nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="/mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>
</pre></blockquote><pre style="margin: 0em;">


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00010" href="msg00010.html">Re: Problem during &quot;final&quot; run of d'Auvergne Protocol</a></strong>
<ul><li><em>From:</em> Hugh RW Dannatt</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="00003" href="msg00003.html">Problem during &quot;final&quot; run of d'Auvergne Protocol</a></strong>
<ul><li><em>From:</em> Hugh RW Dannatt</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Tue Mar 06 13:20:07 2012</div>  
</body>
</html>
