<!-- MHonArc v2.6.10 -->
<!--X-Subject: [bug #7875] Script full_analysis.py shoots error when starting monte	carlo simulations for the final run -->
<!--X-From-R13: Eéonfgvra [beva <@A&#45;DSBZK.W@HOZWR&#45;ORRDSEENtan.bet> -->
<!--X-Date: Tue, 28 Nov 2006 20:49:37 +0100 -->
<!--X-Message-Id: 20061128&#45;194937.sv7147.18934@gna.org -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>[bug #7875] Script full_analysis.py shoots error when starting monte	carlo simulations for the final run -- November 28, 2006 - 20:49</title>
<link rel="stylesheet" type="text/css" href="/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="https://gna.org/images/gna.theme/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />[bug #7875] Script full_analysis.py shoots error when starting monte	carlo simulations for the final run</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00212" class="tabs">Index by Date</a> | <a href="threads.html#00212" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00211.html">Date Prev</a>] [<a href="msg00213.html">Date Next</a>] [<a href="msg00206.html">Thread Prev</a>] [<a href="msg00214.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Sébastien Morin &lt;sebastien.morin.1@xxxxxxxxx&gt;,	Edward d  Auvergne &lt;edward@xxxxxxxxxxxxx&gt;, relax-devel@xxxxxxx</li>
<li class="menuitem">
<em>Date</em>: Tue, 28 Nov 2006 20:49:37 +0100</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00212.html">20061128-194937.sv7147.18934@gna.org</a>&gt;</li>
<li class="menuitem">
<em>References</em>: </li>
<li class="menuitem">
<em>User-agent</em>: Mozilla/5.0 (X11; U; Linux i686; en-US;	rv:1.8.1) Gecko/20061120 Firefox/2.0</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Sébastien Morin</strong> on November 28, 2006 - 20:49:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">

URL:
  &lt;<a  href="http://gna.org/bugs/?7875">http://gna.org/bugs/?7875</a>&gt;

                 Summary: Script full_analysis.py shoots error when starting
monte carlo simulations for the final run
                 Project: relax
            Submitted by: semor
            Submitted on: Tuesday 11/28/2006 at 19:49
                Category: relax's source code
                Severity: 4 - Important
                Priority: 5 - Normal
                  Status: None
                 Privacy: Public
             Assigned to: None
         Originator Name: 
        Originator Email: 
             Open/Closed: Open
         Discussion Lock: Any
                 Release: Repository: 1.2 line
        Operating System: GNU/Linux

    _______________________________________________________

Details:

At revision 2890...

Using the full_analysis.py script for the final optimization, I get the
following error :

========================================================

The model from the run 'local_tm' has been selected.

relax&gt; monte_carlo.setup(run='final', number=200)

relax&gt; monte_carlo.create_data(run='final', method='back_calc')
Traceback (most recent call last):
  File &quot;/home/semor/bin/relax&quot;, line 454, in ?
    Relax()
  File &quot;/home/semor/bin/relax&quot;, line 166, in __init__
    self.interpreter.run()
  File &quot;/2home/packages/relax/prompt/interpreter.py&quot;, line 213, in run
    run_script(intro=self.relax.intro_string, local=self.local,
script_file=self.relax.script_file, quit=1)
  File &quot;/2home/packages/relax/prompt/interpreter.py&quot;, line 388, in
run_script
    console.interact(intro, local, script_file, quit)
  File &quot;/2home/packages/relax/prompt/interpreter.py&quot;, line 340, in
interact_script
    execfile(script_file, local)
  File &quot;./full_analysis_SEMOR_FINAL_200_auto_check.py&quot;, line 566, in ?
    Main(self.relax)
  File &quot;./full_analysis_SEMOR_FINAL_200_auto_check.py&quot;, line 296, in
__init__
    monte_carlo.create_data('final')
  File &quot;/2home/packages/relax/prompt/monte_carlo.py&quot;, line 91, in
create_data
    self.__relax__.generic.monte_carlo.create_data(run=run, method=method)
  File &quot;/2home/packages/relax/generic_fns/monte_carlo.py&quot;, line 78, in
create_data
    data = create_mc_data(self.run, i)
  File &quot;/2home/packages/relax/specific_fns/model_free.py&quot;, line 640, in
create_mc_data
    value = self.back_calc(run=run, index=i,
ri_label=self.relax.data.res[run][i].ri_labels[j],
frq_label=self.relax.data.res[run][i].frq_labels[self.relax.data.res[run][i].remap_table[j]],
frq=self.relax.data.res[run][i].frq[self.relax.data.res[run][i].remap_table[j]])
  File &quot;/2home/packages/relax/specific_fns/model_free.py&quot;, line 399, in
back_calc
    value = self.minimise(run=self.run, min_algor='back_calc',
min_options=(index, ri_label, frq_label, frq))
  File &quot;/2home/packages/relax/specific_fns/model_free.py&quot;, line 2025, in
minimise
    if not self.relax.data.res[self.run][i].model:
AttributeError: Element instance has no attribute 'model'






    _______________________________________________________

Reply to this item at:

  &lt;<a  href="http://gna.org/bugs/?7875">http://gna.org/bugs/?7875</a>&gt;

_______________________________________________
  Message sent via/by Gna!
  <a  href="http://gna.org/">http://gna.org/</a>



</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00214" href="msg00214.html">[bug #7875] Script full_analysis.py shoots error when starting monte	carlo simulations for the final run</a></strong>
<ul><li><em>From:</em> Edward d Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer">You are on the <a href="http://gna.org">Gna!</a> mail server.</div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Thu Nov 30 11:00:54 2006</div>  
</body>
</html>
