<!-- MHonArc v2.6.19+ -->
<!--X-Subject: Error in model free analysis -->
<!--X-From-R13: Ofuvfu Erguv &#60;nfuvfu.frguvNhavzryo.rqh.nh> -->
<!--X-Date: Wed, 22 Feb 2017 08:57:06 +0100 -->
<!--X-Message-Id: ME1PR01MB142726D94BF3D275157584E4AB500@ME1PR01MB1427.ausprd01.prod.outlook.com -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Error in model free analysis -- February 22, 2017 - 08:57</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Error in model free analysis</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00007" class="tabs">Index by Date</a> | <a href="threads.html#00007" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00006.html">Date Prev</a>] [<a href="msg00008.html">Date Next</a>] [<a href="msg00006.html">Thread Prev</a>] [<a href="msg00008.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: &quot;relax-users@xxxxxxx&quot; &lt;relax-users@xxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Wed, 22 Feb 2017 07:56:47 +0000</li>
<li class="menuitem">
<em>Accept-language</em>: en-US</li>
<li class="menuitem">
<em>Dkim-signature</em>: v=1; a=rsa-sha256; c=relaxed/relaxed; d=unimelb.edu.au; s=mimecast20161020; t=1487750212; bh=uTvTFxB3g1yv+J9whjv9iLsgyb6YWbLdH1LttEx236w=; h=From:To:Subject:Date:Message-ID:MIME-Version:Content-Type; b=eObrcfwMT+qFzuq7muNwZ1lITmv7V2SDcaPxZG0cH3tDweXAMOQmnHrOAEFAJuZtZ3j6er9LziRXHWHv4IybwJEwksWL/Ge9/ZeM7yhqk2Sn9gsi0trca8V5e3JTe9ySzFjdpbHcEfxGuzQgfumM2qSMyOeG3EKqqatI8SlL7YE=</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00007.html">ME1PR01MB142726D94BF3D275157584E4AB500@ME1PR01MB1427.ausprd01.prod.outlook.com</a>&gt;</li>
<li class="menuitem">
<em>Spamdiagnosticmetadata</em>: NSPM</li>
<li class="menuitem">
<em>Spamdiagnosticoutput</em>: 1:99</li>
<li class="menuitem">
<em>Thread-index</em>: AQHSjODo+vYVhKmelU2PNKfg15StxQ==</li>
<li class="menuitem">
<em>Thread-topic</em>: Error in model free analysis</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Ashish Sethi</strong> on February 22, 2017 - 08:57:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Dear Edward,



I also tried running the same calculation on my personal macbook pro (OSx EI 
Capitan) and I got the following errors:


relax&gt; results.read(file='results', dir='/Users/ashishsethi/Desktop/model 
free LDLamodule/local_tm/aic')

Opening the file '/Users/ashishsethi/Desktop/model free 
LDLamodule/local_tm/aic/results.bz2' for reading.

Exception raised in thread.


Traceback (most recent call last):

  File &quot;gui/analyses/execute.pyc&quot;, line 87, in run

  File &quot;gui/analyses/auto_model_free.pyc&quot;, line 811, in run_analysis

  File &quot;auto_analyses/dauvergne_protocol.pyc&quot;, line 246, in __init__

  File &quot;auto_analyses/dauvergne_protocol.pyc&quot;, line 652, in execute

  File &quot;prompt/uf_objects.pyc&quot;, line 225, in __call__

  File &quot;pipe_control/results.pyc&quot;, line 97, in read

  File &quot;data_store/__init__.pyc&quot;, line 512, in from_xml

  File &quot;data_store/pipe_container.pyc&quot;, line 244, in from_xml

  File &quot;lib/structure/internal/object.pyc&quot;, line 1714, in from_xml

  File &quot;lib/structure/internal/models.pyc&quot;, line 155, in from_xml

  File &quot;lib/structure/internal/molecules.pyc&quot;, line 632, in from_xml

  File &quot;lib/structure/internal/molecules.pyc&quot;, line 449, in from_xml

  File &quot;lib/xml.pyc&quot;, line 287, in xml_to_object

  File &quot;lib/float.pyc&quot;, line 200, in packBytesAsPyFloat

error: pack expected 8 items for packing (got 571)



I have attached the results.bz2 file with this email.



Thanks


Ashish

</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00008" href="msg00008.html">Re: Error in model free analysis</a></strong>
<ul><li><em>From:</em> Troels Emtek√¶r Linnet</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Wed Feb 22 10:20:21 2017</div>  
</body>
</html>
