<!-- MHonArc v2.6.16 -->
<!--X-Subject: [bug #19528] MemoryError during "final" run of d'Auvergne Protocol -->
<!--X-From-R13: nabalzbhf <@A&#45;DSBZK.W@HOZWR&#45;ORRDSEENtan.bet> -->
<!--X-Date: Tue, 06 Mar 2012 12:25:35 +0100 -->
<!--X-Message-Id: 20120306&#45;112534.sv0.26153@gna.org -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>[bug #19528] MemoryError during &quot;final&quot; run of d'Auvergne Protocol -- March 06, 2012 - 12:25</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />[bug #19528] MemoryError during &quot;final&quot; run of d'Auvergne Protocol</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00000" class="tabs">Index by Date</a> | <a href="threads.html#00000" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[Date Prev] [<a href="msg00001.html">Date Next</a>] [Thread Prev] [<a href="msg00001.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: h.dannatt@xxxxxxxxxx, relax-devel@xxxxxxx</li>
<li class="menuitem">
<em>Date</em>: Tue, 06 Mar 2012 12:25:34 +0100</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00000.html">20120306-112534.sv0.26153@gna.org</a>&gt;</li>
<li class="menuitem">
<em>References</em>: </li>
<li class="menuitem">
<em>User-agent</em>: Mozilla/5.0 (X11; Ubuntu; Linux i686;	rv:10.0.1) Gecko/20100101 Firefox/10.0.1</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>anonymous</strong> on March 06, 2012 - 12:25:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">URL:
  &lt;<a  rel="nofollow" href="http://gna.org/bugs/?19528">http://gna.org/bugs/?19528</a>&gt;

                 Summary: MemoryError during &quot;final&quot; run of d'Auvergne
Protocol
                 Project: relax
            Submitted by: None
            Submitted on: Tue Mar  6 11:25:33 2012
                Category: relax's source code
                Severity: 4 - Important
                Priority: 5 - Normal
                  Status: None
                 Privacy: Public
             Assigned to: None
         Originator Name: Hugh Dannatt
        Originator Email: h.dannatt@xxxxxxxxxx
             Open/Closed: Open
         Discussion Lock: Any
                 Release: 1.3.13
        Operating System: GNU/Linux

    _______________________________________________________

Details:

Following the generation and fitting of 500 MC simulations, the program stops
outputting anything onto the screen for several hours, during which time the
computer gradually gets slower and slower. Eventually the program fails and
outputs a &quot;MemoryError&quot; message to screen, such as the one below. A reduction
of the number of MC simulations to as large a number as 100 relieves this
problem.

Believed to be a recursive exception in the multi-processor framework.

--------

Simulation 495
Simulation 496
Simulation 497
Simulation 498
Simulation 499
Simulation 500


Traceback (most recent call last):
  File &quot;/progs/relax-1.3.13/multi/uni_processor.py&quot;, line 136, in run
    self.callback.init_master(self)
  File &quot;/progs/relax-1.3.13/multi/processor.py&quot;, line 263, in
default_init_maste
r
    self.master.run()
  File &quot;/progs/relax-1.3.13/relax.py&quot;, line 171, in run
    self.interpreter.run(self.script_file)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 300, in run
    return run_script(intro=self.__intro_string, local=locals(),
script_file=scr
ipt_file, quit=self.__quit_flag, show_script=self.__show_script,
raise_relax_err
or=self.__raise_relax_error)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 610, in run_script
    return console.interact(intro, local, script_file, quit,
show_script=show_sc
ript, raise_relax_error=raise_relax_error)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 495, in
interact_script
    exec_script(script_file, local)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 383, in exec_script
    runpy.run_module(module, globals)
  File &quot;/usr/lib/python2.6/runpy.py&quot;, line 140, in run_module
    fname, loader, pkg_name)
  File &quot;/usr/lib/python2.6/runpy.py&quot;, line 34, in _run_code
    exec code in run_globals
  File &quot;/home1/hugh/data/pgm298bq/relax/dauvergne_protocol.py&quot;, line 216, in
&lt;mo
dule&gt;
    dAuvergne_protocol(pipe_name=name, diff_model=DIFF_MODEL,
mf_models=MF_MODEL
S, local_tm_models=LOCAL_TM_MODELS, grid_inc=GRID_INC, min_algor=MIN_ALGOR,
mc_s
im_num=MC_NUM, conv_loop=CONV_LOOP)
  File &quot;/progs/relax-1.3.13/auto_analyses/dauvergne_protocol.py&quot;, line 223, in
_
_init__
Traceback (most recent call last):
  File &quot;/progs/Linux/bin/relax13&quot;, line 7, in &lt;module&gt;
    relax.start()
  File &quot;/progs/relax-1.3.13/relax.py&quot;, line 100, in start
    processor.run()
  File &quot;/progs/relax-1.3.13/multi/uni_processor.py&quot;, line 139, in run
    self.callback.handle_exception(self, e)
  File &quot;/progs/relax-1.3.13/multi/processor.py&quot;, line 250, in
default_handle_exc
eption
    traceback.print_exc(file=sys.stderr)
  File &quot;/usr/lib/python2.6/traceback.py&quot;, line 227, in print_exc
    print_exception(etype, value, tb, limit, file)
  File &quot;/usr/lib/python2.6/traceback.py&quot;, line 125, in print_exception
    print_tb(tb, limit, file)
  File &quot;/usr/lib/python2.6/traceback.py&quot;, line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File &quot;/usr/lib/python2.6/linecache.py&quot;, line 14, in getline
    lines = getlines(filename, module_globals)
  File &quot;/usr/lib/python2.6/linecache.py&quot;, line 40, in getlines
    return updatecache(filename, module_globals)
  File &quot;/usr/lib/python2.6/linecache.py&quot;, line 136, in updatecache
    lines = fp.readlines()
MemoryError
9078.655u 666.933s 10:55:29.66 24.7%    0+0k 241482000+0io 6665721pf+0w




    _______________________________________________________

Reply to this item at:

  &lt;<a  rel="nofollow" href="http://gna.org/bugs/?19528">http://gna.org/bugs/?19528</a>&gt;

_______________________________________________
  Message sent via/by Gna!
  <a  rel="nofollow" href="http://gna.org/">http://gna.org/</a>



</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00001" href="msg00001.html">[bug #19528] MemoryError during &quot;final&quot; run of d'Auvergne Protocol</a></strong>
<ul><li><em>From:</em> Edward d Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Thu Mar 22 12:00:12 2012</div>  
</body>
</html>
